<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>OpenLiveWriter.CoreServices</AssemblyName>
    <RootNamespace>OpenLiveWriter.CoreServices</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="**\*.cs" Exclude="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.resx" />
    <EmbeddedResource Include="**\*.png" />
    <EmbeddedResource Include="**\*.jpg" />
    <EmbeddedResource Include="**\*.ico" />
    <EmbeddedResource Include="**\*.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketXmlGenerator\MarketXmlGenerator.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.BrowserControl\OpenLiveWriter.BrowserControl.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.HtmlParser\OpenLiveWriter.HtmlParser.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Interop\OpenLiveWriter.Interop.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Interop.Mshtml\OpenLiveWriter.Interop.Mshtml.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Localization\OpenLiveWriter.Localization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OpenLiveWriter.Interop.SHDocVw">
      <HintPath>..\OpenLiveWriter.Interop\Com\OpenLiveWriter.Interop.SHDocVw.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>