//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSnippet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeSnippet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alternate_line_bkg {
            get {
                object obj = ResourceManager.GetObject("alternate_line_bkg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blog_logo {
            get {
                object obj = ResourceManager.GetObject("blog_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string CategoryAttribute_Attributes {
            get {
                return ResourceManager.GetString("CategoryAttribute_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string CategoryAttribute_Styles {
            get {
                return ResourceManager.GetString("CategoryAttribute_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clipboard_clear {
            get {
                object obj = ResourceManager.GetObject("clipboard_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CodeSnippet {
            get {
                object obj = ResourceManager.GetObject("CodeSnippet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CodeSnippetIcon {
            get {
                object obj = ResourceManager.GetObject("CodeSnippetIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string ConfigSectionName_Editor {
            get {
                return ResourceManager.GetString("ConfigSectionName_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ConfigSectionName_General {
            get {
                return ResourceManager.GetString("ConfigSectionName_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string ConfigSectionName_Layout {
            get {
                return ResourceManager.GetString("ConfigSectionName_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string ConfigSectionName_Styles {
            get {
                return ResourceManager.GetString("ConfigSectionName_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSS styles used in this plugin have been copied to the Clipboard. You can now paste them in your Blog&apos;s master template or in one of your style files that is loaded as part of your blog.
        ///
        ///Make sure to clear the Embed Styles option to ensure the main styles are used. Otherwise, the styles will always be embedded and they will override modifications you may have made to customize the layout of code snippets..
        /// </summary>
        internal static string CopyStyles {
            get {
                return ResourceManager.GetString("CopyStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View mode driving the layout of the Code Snippet dialog. It can be either Compact or Full..
        /// </summary>
        internal static string DescriptionAttribute_ActiveMode {
            get {
                return ResourceManager.GetString("DescriptionAttribute_ActiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active view type driving the main workspace area of the Code Snippet dialog. It can be one of CodeSnippet, FormattedCodeSnippet, or Both..
        /// </summary>
        internal static string DescriptionAttribute_ActiveView {
            get {
                return ResourceManager.GetString("DescriptionAttribute_ActiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether or not lines will have alternating background colors..
        /// </summary>
        internal static string DescriptionAttribute_AlternateLines {
            get {
                return ResourceManager.GetString("DescriptionAttribute_AlternateLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for the even alternating lines of code..
        /// </summary>
        internal static string DescriptionAttribute_AltevenStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_AltevenStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for the odd alternating lines of code..
        /// </summary>
        internal static string DescriptionAttribute_AltStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_AltStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for lines containing ASP code..
        /// </summary>
        internal static string DescriptionAttribute_AspStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_AspStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for attributes in HTML code..
        /// </summary>
        internal static string DescriptionAttribute_AttrStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_AttrStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for classes..
        /// </summary>
        internal static string DescriptionAttribute_ClsStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_ClsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for the lines of code when line numbers or alternate lines are not enabled..
        /// </summary>
        internal static string DescriptionAttribute_CodeStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_CodeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether or not the CSS styles used will be embedded with the HTML output..
        /// </summary>
        internal static string DescriptionAttribute_EmbedStyles {
            get {
                return ResourceManager.GetString("DescriptionAttribute_EmbedStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for HTML code..
        /// </summary>
        internal static string DescriptionAttribute_HtmlStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_HtmlStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for reserved keywords..
        /// </summary>
        internal static string DescriptionAttribute_KwrdStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_KwrdStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether or not line numbers are generated..
        /// </summary>
        internal static string DescriptionAttribute_LineNumbers {
            get {
                return ResourceManager.GetString("DescriptionAttribute_LineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for line numbers..
        /// </summary>
        internal static string DescriptionAttribute_LnumStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_LnumStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for operators..
        /// </summary>
        internal static string DescriptionAttribute_OpStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_OpStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for preprocessor keywords..
        /// </summary>
        internal static string DescriptionAttribute_PreprocStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_PreprocStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for the lines of code when line numbers or alternate lines are enabled..
        /// </summary>
        internal static string DescriptionAttribute_PreStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_PreStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for comments..
        /// </summary>
        internal static string DescriptionAttribute_RemStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_RemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether or not to run in silent mode. Silent mode allows for the quick pasting of formatted source code using the last configuration..
        /// </summary>
        internal static string DescriptionAttribute_RunSilent {
            get {
                return ResourceManager.GetString("DescriptionAttribute_RunSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the section being viewed..
        /// </summary>
        internal static string DescriptionAttribute_SectionName {
            get {
                return ResourceManager.GetString("DescriptionAttribute_SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for strings..
        /// </summary>
        internal static string DescriptionAttribute_StrStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_StrStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading style sheet definitions for different code snippet styles..
        /// </summary>
        internal static string DescriptionAttribute_Styles {
            get {
                return ResourceManager.GetString("DescriptionAttribute_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of space characters to substitute for tab characters..
        /// </summary>
        internal static string DescriptionAttribute_TabSpaces {
            get {
                return ResourceManager.GetString("DescriptionAttribute_TabSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether or not to trim TAB characters from the beginning of lines when being pasted..
        /// </summary>
        internal static string DescriptionAttribute_TrimIndentOnPaste {
            get {
                return ResourceManager.GetString("DescriptionAttribute_TrimIndentOnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether or not to use a container for the generated code..
        /// </summary>
        internal static string DescriptionAttribute_UseContainer {
            get {
                return ResourceManager.GetString("DescriptionAttribute_UseContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether word-wrapping is enabled in the view..
        /// </summary>
        internal static string DescriptionAttribute_WordWrap {
            get {
                return ResourceManager.GetString("DescriptionAttribute_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style used for the wrapping container of the code snippet..
        /// </summary>
        internal static string DescriptionAttribute_WrapperStyle {
            get {
                return ResourceManager.GetString("DescriptionAttribute_WrapperStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Mode.
        /// </summary>
        internal static string DisplayNameAttribute_ActiveMode {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_ActiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active View.
        /// </summary>
        internal static string DisplayNameAttribute_ActiveView {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_ActiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Lines.
        /// </summary>
        internal static string DisplayNameAttribute_AlternateLines {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_AlternateLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Styles.
        /// </summary>
        internal static string DisplayNameAttribute_EmbedStyles {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_EmbedStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Numbers.
        /// </summary>
        internal static string DisplayNameAttribute_LineNumbers {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_LineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Silent.
        /// </summary>
        internal static string DisplayNameAttribute_RunSilent {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_RunSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name.
        /// </summary>
        internal static string DisplayNameAttribute_SectionName {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string DisplayNameAttribute_Style {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Spaces.
        /// </summary>
        internal static string DisplayNameAttribute_TabSpaces {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_TabSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Indent on Paste.
        /// </summary>
        internal static string DisplayNameAttribute_TrimIndentOnPaste {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_TrimIndentOnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Container.
        /// </summary>
        internal static string DisplayNameAttribute_UseContainer {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_UseContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        internal static string DisplayNameAttribute_WordWrap {
            get {
                return ResourceManager.GetString("DisplayNameAttribute_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editor {
            get {
                object obj = ResourceManager.GetObject("editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - http://lvildosola.blogspot.com.
        /// </summary>
        internal static string FormAbout_Company {
            get {
                return ResourceManager.GetString("FormAbout_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string FormAbout_Title {
            get {
                return ResourceManager.GetString("FormAbout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build {0}.
        /// </summary>
        internal static string FormAbout_Version {
            get {
                return ResourceManager.GetString("FormAbout_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap full_mode {
            get {
                object obj = ResourceManager.GetObject("full_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap general {
            get {
                object obj = ResourceManager.GetObject("general", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layers {
            get {
                object obj = ResourceManager.GetObject("layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layout {
            get {
                object obj = ResourceManager.GetObject("layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_code {
            get {
                object obj = ResourceManager.GetObject("page_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_word_wrap {
            get {
                object obj = ResourceManager.GetObject("page_word_wrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected text is not recognized as a code snippet previously generated by the plugin. However, you may still attempt to load the text to process as a code snippet.
        ///
        ///Would you like to treat the selected text as a code snippet and edit it?.
        /// </summary>
        internal static string ProcessSelectedTextAsCodeSnippet {
            get {
                return ResourceManager.GetString("ProcessSelectedTextAsCodeSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string PropertyGrid_DefaultDisplayValue {
            get {
                return ResourceManager.GetString("PropertyGrid_DefaultDisplayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Silent mode will cause the plugin to process the contents of the clipboard without displaying the dialog. Once enabled, the plugin will perform all processing in the background. The processing will be done with the latest settings configured.
        ///
        ///To turn off Run Silent mode, hold down the &apos;Ctrl&apos; key while executing the command that launches the plugin. Continue holding until the dialog appears.
        ///
        ///If you enable Run Silent mode this dialog instance will close and any in-process data will be discarded. You [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunningSilent {
            get {
                return ResourceManager.GetString("RunningSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap style {
            get {
                object obj = ResourceManager.GetObject("style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap style_add {
            get {
                object obj = ResourceManager.GetObject("style_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap style_edit {
            get {
                object obj = ResourceManager.GetObject("style_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag {
            get {
                object obj = ResourceManager.GetObject("tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_indent {
            get {
                object obj = ResourceManager.GetObject("text_indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_indent_remove {
            get {
                object obj = ResourceManager.GetObject("text_indent_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_list_numbers {
            get {
                object obj = ResourceManager.GetObject("text_list_numbers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Snippet (GWN).
        /// </summary>
        internal static string WriterPlugin_Name {
            get {
                return ResourceManager.GetString("WriterPlugin_Name", resourceCulture);
            }
        }
    }
}
