<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>OpenLiveWriter.HtmlParser</AssemblyName>
    <RootNamespace>OpenLiveWriter.HtmlParser</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="FormAgent\*.cs" />
    <Compile Include="Parser\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="FormAgent\test1.htm" />
  </ItemGroup>

</Project>
