<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>OpenLiveWriter.BrowserControl</AssemblyName>
    <RootNamespace>OpenLiveWriter.BrowserControl</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="**\*.cs" Exclude="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ExplorerBrowserControl.resx">
      <DependentUpon>ExplorerBrowserControl.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenLiveWriter.Interop\OpenLiveWriter.Interop.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Interop.Mshtml\OpenLiveWriter.Interop.Mshtml.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OpenLiveWriter.Interop.SHDocVw">
      <HintPath>..\OpenLiveWriter.Interop\Com\OpenLiveWriter.Interop.SHDocVw.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
