<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLiveWriter.InternalWriterPlugin</AssemblyName>
    <RootNamespace>OpenLiveWriter.InternalWriterPlugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="**\*.cs" Exclude="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.resx" />
    <EmbeddedResource Include="**\*.png" Exclude="obj\**" />
    <EmbeddedResource Include="**\*.gif" Exclude="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="map-preview.html" CopyToOutputDirectory="PreserveNewest" Link="html\map-preview.html" />
    <Content Include="map.html" CopyToOutputDirectory="PreserveNewest" Link="html\map.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenLiveWriter.Api\OpenLiveWriter.Api.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.ApplicationFramework\OpenLiveWriter.ApplicationFramework.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.BrowserControl\OpenLiveWriter.BrowserControl.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Controls\OpenLiveWriter.Controls.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.CoreServices\OpenLiveWriter.CoreServices.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Interop.Mshtml\OpenLiveWriter.Interop.Mshtml.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Interop\OpenLiveWriter.Interop.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Localization\OpenLiveWriter.Localization.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Mshtml\OpenLiveWriter.Mshtml.csproj" />
  </ItemGroup>
</Project>