<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLiveWriter.UnitTest</AssemblyName>
    <RootNamespace>OpenLiveWriter.UnitTest</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="**\*.cs" Exclude="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CoreServices\ResourceDownloading\SupportingCabs\*.cab" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenLiveWriter.Api\OpenLiveWriter.Api.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.CoreServices\OpenLiveWriter.CoreServices.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Extensibility\OpenLiveWriter.Extensibility.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.HtmlEditor\OpenLiveWriter.HtmlEditor.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.Interop\OpenLiveWriter.Interop.csproj" />
    <ProjectReference Include="..\OpenLiveWriter.PostEditor\OpenLiveWriter.PostEditor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interop\" />
  </ItemGroup>
</Project>