<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LocEdit</AssemblyName>
    <RootNamespace>LocEdit</RootNamespace>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="**\*.cs" Exclude="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocUtil\LocUtil.csproj" />
  </ItemGroup>
</Project>