// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using NUnit.Framework;
using OpenLiveWriter.HtmlParser.Parser;

namespace OpenLiveWriter.Tests.HtmlParser
{
    /// <summary>
    /// Tests for HtmlUtils.FixNestedListHtml which fixes invalid nested list HTML
    /// generated by MSHTML where nested ul/ol elements appear as siblings of li
    /// instead of being nested inside the preceding li.
    /// </summary>
    [TestFixture]
    public class NestedListFixTests
    {
        [Test]
        public void NullAndEmptyInput()
        {
            Assert.IsNull(HtmlUtils.FixNestedListHtml(null));
            Assert.AreEqual("", HtmlUtils.FixNestedListHtml(""));
        }

        [Test]
        public void ValidNestedList_Preserved()
        {
            // Already valid nested list should be unchanged
            string valid = "<ul><li>item 1</li><li>item 2<ul><li>nested</li></ul></li></ul>";
            Assert.AreEqual(valid, HtmlUtils.FixNestedListHtml(valid));
        }

        [Test]
        public void FlatList_Preserved()
        {
            // Simple flat list should be unchanged
            string flat = "<ul><li>item 1</li><li>item 2</li><li>item 3</li></ul>";
            Assert.AreEqual(flat, HtmlUtils.FixNestedListHtml(flat));
        }

        [Test]
        public void InvalidNestedUl_Fixed()
        {
            // MSHTML-style invalid nesting: <ul> as sibling of <li>
            string input = "<ul><li>item 1</li><li>item 2</li><ul><li>nested</li></ul></ul>";
            string expected = "<ul><li>item 1</li><li>item 2<ul><li>nested</li></ul></li></ul>";
            Assert.AreEqual(expected, HtmlUtils.FixNestedListHtml(input));
        }

        [Test]
        public void InvalidNestedOl_Fixed()
        {
            // Same issue with ordered lists
            string input = "<ol><li>item 1</li><li>item 2</li><ol><li>nested</li></ol></ol>";
            string expected = "<ol><li>item 1</li><li>item 2<ol><li>nested</li></ol></li></ol>";
            Assert.AreEqual(expected, HtmlUtils.FixNestedListHtml(input));
        }

        [Test]
        public void MixedNestedLists_Fixed()
        {
            // UL nested inside OL
            string input = "<ol><li>item 1</li><li>item 2</li><ul><li>nested</li></ul></ol>";
            string expected = "<ol><li>item 1</li><li>item 2<ul><li>nested</li></ul></li></ol>";
            Assert.AreEqual(expected, HtmlUtils.FixNestedListHtml(input));
        }

        [Test]
        public void MultipleNestedLevels_Fixed()
        {
            // Three levels of nesting
            string input = "<ul><li>item 1</li><ul><li>nested 1</li><ul><li>deep nested</li></ul></ul></ul>";
            string expected = "<ul><li>item 1<ul><li>nested 1<ul><li>deep nested</li></ul></li></ul></li></ul>";
            Assert.AreEqual(expected, HtmlUtils.FixNestedListHtml(input));
        }

        [Test]
        public void MultipleNestedSiblings_Fixed()
        {
            // Multiple items with nested sublists
            string input = "<ul><li>item 1</li><ul><li>sub 1</li></ul><li>item 2</li><ul><li>sub 2</li></ul></ul>";
            string expected = "<ul><li>item 1<ul><li>sub 1</li></ul></li><li>item 2<ul><li>sub 2</li></ul></li></ul>";
            Assert.AreEqual(expected, HtmlUtils.FixNestedListHtml(input));
        }

        [Test]
        public void NoListContent_Preserved()
        {
            // Non-list content should pass through unchanged
            string noList = "<div><p>Hello</p><p>World</p></div>";
            Assert.AreEqual(noList, HtmlUtils.FixNestedListHtml(noList));
        }

        [Test]
        public void ListWithAttributes_Preserved()
        {
            // Lists with attributes should be handled correctly
            string input = "<ul class=\"main\"><li>item</li><ul class=\"sub\"><li>nested</li></ul></ul>";
            string expected = "<ul class=\"main\"><li>item<ul class=\"sub\"><li>nested</li></ul></li></ul>";
            Assert.AreEqual(expected, HtmlUtils.FixNestedListHtml(input));
        }
    }
}
