<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>OpenLiveWriter.Localization</AssemblyName>
    <RootNamespace>OpenLiveWriter.Localization</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="Bidi\*.cs" />
    <Compile Include="*.cs" Exclude="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Images.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="PropertiesNonLoc.resx" />
    <EmbeddedResource Include="Properties.resx" />
    <EmbeddedResource Include="Strings.resx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Commands.xml" />
    <Content Include="DisplayMessages.xml" />
    <Content Include="CommandBitmaps\**\*" />
    <Content Include="Emoticons\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenLiveWriter.Interop\OpenLiveWriter.Interop.csproj" />
  </ItemGroup>

</Project>