// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

namespace mshtml
{
    using System;

    public enum _BEHAVIOR_RENDER_INFO
    {
        BEHAVIOR_RENDER_INFO_Max = 0x7fffffff,
        BEHAVIORRENDERINFO_3DSURFACE = 0x200000,
        BEHAVIORRENDERINFO_ABOVECONTENT = 40,
        BEHAVIORRENDERINFO_AFTERBACKGROUND = 2,
        BEHAVIORRENDERINFO_AFTERCONTENT = 8,
        BEHAVIORRENDERINFO_AFTERFOREGROUND = 0x20,
        BEHAVIORRENDERINFO_ALLLAYERS = 0xff,
        BEHAVIORRENDERINFO_BEFOREBACKGROUND = 1,
        BEHAVIORRENDERINFO_BEFORECONTENT = 4,
        BEHAVIORRENDERINFO_DISABLEALLLAYERS = 0xf00,
        BEHAVIORRENDERINFO_DISABLEBACKGROUND = 0x100,
        BEHAVIORRENDERINFO_DISABLECONTENT = 0x400,
        BEHAVIORRENDERINFO_DISABLENEGATIVEZ = 0x200,
        BEHAVIORRENDERINFO_DISABLEPOSITIVEZ = 0x800,
        BEHAVIORRENDERINFO_HITTESTING = 0x1000,
        BEHAVIORRENDERINFO_SURFACE = 0x100000
    }
}

