<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>OpenLiveWriter.Interop</AssemblyName>
    <RootNamespace>OpenLiveWriter.Interop</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
    <Compile Include="Com\**\*.cs" />
    <Compile Include="Windows\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Com\OpenLiveWriter.Interop.SHDocVw.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
